// California cities - comprehensive list

export const CALIFORNIA_CITIES = [
  // Major Cities & Metropolitan Areas
  'Los Angeles',
  'San Diego',
  'San Jose',
  'San Francisco',
  'Fresno',
  'Sacramento',
  'Long Beach',
  'Oakland',
  'Bakersfield',
  'Anaheim',

  // Bay Area
  'San Francisco',
  'Oakland',
  'San Jose',
  'Fremont',
  'Santa Clara',
  'Sunnyvale',
  'Hayward',
  'Concord',
  'Berkeley',
  'Richmond',
  'Antioch',
  'Daly City',
  'San Mateo',
  'Vallejo',
  'Livermore',
  'San Leandro',
  'Fairfield',
  'Redwood City',
  'Mountain View',
  'Alameda',
  'Palo Alto',
  'Vacaville',
  'South San Francisco',
  'San Rafael',
  'Union City',
  'Napa',
  'Pleasanton',
  'Milpitas',
  'Cupertino',
  'Walnut Creek',
  'Novato',
  'San Bruno',
  'Pittsburg',
  'Petaluma',
  'San Ramon',
  'Menlo Park',
  'Campbell',
  'Santa Rosa',

  // Central Coast
  'Santa Cruz',
  'Monterey',
  'Salinas',
  'Seaside',
  'Watsonville',
  'Hollister',
  'Gilroy',
  'Santa Maria',
  'San Luis Obispo',
  'Paso Robles',
  'Atascadero',
  'Morro Bay',
  'Pismo Beach',
  'Arroyo Grande',
  'Capitola',
  'Aptos',
  'Scotts Valley',
  'Carmel-by-the-Sea',
  'Pacific Grove',
  'Marina',
  'King City',
  'Gonzales',
  'Soledad',
  'Greenfield',

  // Los Angeles County
  'Los Angeles',
  'Long Beach',
  'Glendale',
  'Santa Clarita',
  'Lancaster',
  'Palmdale',
  'Pomona',
  'Torrance',
  'Pasadena',
  'El Monte',
  'Downey',
  'Inglewood',
  'West Covina',
  'Norwalk',
  'Burbank',
  'Compton',
  'South Gate',
  'Carson',
  'Santa Monica',
  'Hawthorne',
  'Alhambra',
  'Lakewood',
  'Whittier',
  'Bellflower',
  'Baldwin Park',
  'Redondo Beach',
  'Montebello',
  'Pico Rivera',
  'Monterey Park',
  'Gardena',
  'Culver City',
  'Manhattan Beach',
  'Beverly Hills',
  'Arcadia',
  'Monrovia',
  'Azusa',
  'Glendora',
  'La Puente',
  'Paramount',
  'West Hollywood',
  'Malibu',

  // Orange County
  'Anaheim',
  'Santa Ana',
  'Irvine',
  'Huntington Beach',
  'Garden Grove',
  'Fullerton',
  'Orange',
  'Costa Mesa',
  'Mission Viejo',
  'Westminster',
  'Newport Beach',
  'Buena Park',
  'Lake Forest',
  'Tustin',
  'Yorba Linda',
  'San Clemente',
  'Laguna Niguel',
  'La Habra',
  'Fountain Valley',
  'Placentia',
  'Rancho Santa Margarita',
  'Aliso Viejo',
  'Brea',
  'Laguna Beach',
  'Dana Point',
  'Seal Beach',

  // San Diego County
  'San Diego',
  'Chula Vista',
  'Oceanside',
  'Escondido',
  'Carlsbad',
  'El Cajon',
  'Vista',
  'San Marcos',
  'Encinitas',
  'National City',
  'La Mesa',
  'Santee',
  'Poway',
  'Imperial Beach',
  'Coronado',
  'Del Mar',
  'Solana Beach',
  'Lemon Grove',

  // Inland Empire
  'Riverside',
  'San Bernardino',
  'Moreno Valley',
  'Fontana',
  'Rancho Cucamonga',
  'Ontario',
  'Corona',
  'Victorville',
  'Murrieta',
  'Temecula',
  'Hesperia',
  'Hemet',
  'Chino',
  'Chino Hills',
  'Redlands',
  'Menifee',
  'Perris',
  'Lake Elsinore',
  'Eastvale',
  'Yucaipa',
  'Upland',
  'Rialto',
  'Colton',
  'Highland',
  'San Jacinto',
  'Apple Valley',
  'Indio',
  'Palm Springs',
  'Palm Desert',
  'Cathedral City',
  'Coachella',
  'La Quinta',
  'Desert Hot Springs',

  // Central Valley
  'Fresno',
  'Bakersfield',
  'Stockton',
  'Modesto',
  'Visalia',
  'Clovis',
  'Merced',
  'Turlock',
  'Madera',
  'Tulare',
  'Porterville',
  'Hanford',
  'Delano',
  'Lodi',
  'Manteca',
  'Tracy',
  'Ceres',
  'Reedley',
  'Dinuba',
  'Selma',
  'Kingsburg',
  'Sanger',
  'Exeter',

  // Sacramento Region
  'Sacramento',
  'Elk Grove',
  'Roseville',
  'Folsom',
  'Citrus Heights',
  'Rancho Cordova',
  'Rocklin',
  'Davis',
  'Woodland',
  'West Sacramento',
  'Lincoln',
  'Auburn',
  'Yuba City',
  'Marysville',
  'Placerville',

  // Northern California
  'Redding',
  'Chico',
  'Eureka',
  'Ukiah',
  'Crescent City',
  'Yreka',
  'Red Bluff',
  'Oroville',
  'Paradise',
  'Arcata',
  'Fort Bragg',

  // Ventura County
  'Oxnard',
  'Thousand Oaks',
  'Simi Valley',
  'Ventura',
  'Camarillo',
  'Moorpark',
  'Santa Paula',
  'Port Hueneme',

  // San Joaquin Valley
  'Clovis',
  'Visalia',
  'Hanford',
  'Porterville',
  'Tulare',
  'Delano',
];
