// Florida cities - comprehensive list

export const FLORIDA_CITIES = [
  // Major Cities
  'Jacksonville',
  'Miami',
  'Tampa',
  'Orlando',
  'St. Petersburg',
  'Hialeah',
  'Tallahassee',
  'Fort Lauderdale',
  'Port St. Lucie',
  'Cape Coral',

  // South Florida / Miami Metro
  'Miami',
  'Hialeah',
  'Fort Lauderdale',
  'Pembroke Pines',
  'Hollywood',
  'Miramar',
  'Coral Springs',
  'Miami Gardens',
  'Pompano Beach',
  'Davie',
  'Miami Beach',
  'Deerfield Beach',
  'Boca Raton',
  'Delray Beach',
  'Boynton Beach',
  'West Palm Beach',
  'Wellington',
  'Palm Beach Gardens',
  'Jupiter',
  'Royal Palm Beach',
  'Lake Worth',
  'Greenacres',
  'North Miami',
  'North Miami Beach',
  'Aventura',
  'Sunny Isles Beach',
  'Hallandale Beach',
  'Homestead',
  'Florida City',
  'Cutler Bay',
  'Key West',
  'Key Largo',
  'Marathon',
  'Islamorada',

  // Tampa Bay Area
  'Tampa',
  'St. Petersburg',
  'Clearwater',
  'Largo',
  'Pinellas Park',
  'Brandon',
  'Plant City',
  'Temple Terrace',
  'Dunedin',
  'Palm Harbor',
  'Safety Harbor',
  'Tarpon Springs',
  'New Port Richey',
  'Port Richey',
  'Spring Hill',
  'Brooksville',
  'Wesley Chapel',
  'Land O Lakes',
  'Lutz',
  'Riverview',
  'Apollo Beach',
  'Ruskin',

  // Orlando Metro
  'Orlando',
  'Kissimmee',
  'Sanford',
  'Winter Park',
  'Altamonte Springs',
  'Apopka',
  'Oviedo',
  'Winter Garden',
  'Lake Mary',
  'Maitland',
  'Casselberry',
  'Clermont',
  'Leesburg',
  'Mount Dora',
  'Eustis',
  'Longwood',
  'Winter Springs',

  // Southwest Florida
  'Cape Coral',
  'Fort Myers',
  'Naples',
  'Bonita Springs',
  'Estero',
  'Lehigh Acres',
  'North Fort Myers',
  'Port Charlotte',
  'Punta Gorda',
  'Venice',
  'North Port',
  'Sarasota',
  'Bradenton',
  'Palmetto',
  'Lakewood Ranch',

  // Central Florida
  'Lakeland',
  'Winter Haven',
  'Bartow',
  'Haines City',
  'Polk City',
  'Auburndale',
  'Mulberry',
  'Davenport',
  'Sebring',
  'Avon Park',

  // Treasure Coast
  'Port St. Lucie',
  'Fort Pierce',
  'Vero Beach',
  'Stuart',
  'Jensen Beach',
  'Sebastian',

  // Space Coast
  'Palm Bay',
  'Melbourne',
  'Titusville',
  'Cocoa',
  'Cocoa Beach',
  'Merritt Island',
  'Rockledge',
  'Satellite Beach',
  'Indialantic',

  // North Florida
  'Jacksonville',
  'Tallahassee',
  'Gainesville',
  'Ocala',
  'Panama City',
  'Pensacola',
  'Fort Walton Beach',
  'Destin',
  'Niceville',
  'Crestview',
  'St. Augustine',
  'Palm Coast',
  'Daytona Beach',
  'Ormond Beach',
  'Port Orange',
  'DeLand',
  'Deltona',
  'Orange City',
  'Lake City',
  'Live Oak',
  'Palatka',
];
