// US Cities Index - aggregates all state city data

import { CALIFORNIA_CITIES } from './california';
import { TEXAS_CITIES } from './texas';
import { NEW_YORK_CITIES } from './new-york';
import { FLORIDA_CITIES } from './florida';

import {
  PENNSYLVANIA_CITIES,
  NEW_JERSEY_CITIES,
  MASSACHUSETTS_CITIES,
  CONNECTICUT_CITIES,
  RHODE_ISLAND_CITIES,
  VERMONT_CITIES,
  NEW_HAMPSHIRE_CITIES,
  MAINE_CITIES,
} from './northeast';

import {
  ILLINOIS_CITIES,
  OHIO_CITIES,
  MICHIGAN_CITIES,
  WISCONSIN_CITIES,
  MINNESOTA_CITIES,
  MISSOURI_CITIES,
  INDIANA_CITIES,
  IOWA_CITIES,
  KANSAS_CITIES,
  NEBRASKA_CITIES,
  NORTH_DAKOTA_CITIES,
  SOUTH_DAKOTA_CITIES,
} from './midwest';

import {
  GEORGIA_CITIES,
  NORTH_CAROLINA_CITIES,
  SOUTH_CAROLINA_CITIES,
  VIRGINIA_CITIES,
  TENNESSEE_CITIES,
  KENTUCKY_CITIES,
  ALABAMA_CITIES,
  MISSISSIPPI_CITIES,
  LOUISIANA_CITIES,
  ARKANSAS_CITIES,
  WEST_VIRGINIA_CITIES,
} from './southeast';

import {
  ARIZONA_CITIES,
  NEW_MEXICO_CITIES,
  NEVADA_CITIES,
  COLORADO_CITIES,
  UTAH_CITIES,
  IDAHO_CITIES,
  MONTANA_CITIES,
  WYOMING_CITIES,
  OKLAHOMA_CITIES,
} from './southwest-mountain';

import {
  WASHINGTON_CITIES,
  OREGON_CITIES,
  ALASKA_CITIES,
  HAWAII_CITIES,
  DELAWARE_CITIES,
  MARYLAND_CITIES,
  WASHINGTON_DC_CITIES,
} from './pacific-northwest';

import type { StateProvinceName } from '../types';

// Map state names to their city arrays
export const US_CITIES_BY_STATE: { [key in StateProvinceName]?: string[] } = {
  // Large states with individual files
  California: CALIFORNIA_CITIES,
  Texas: TEXAS_CITIES,
  'New York': NEW_YORK_CITIES,
  Florida: FLORIDA_CITIES,

  // Northeast
  Pennsylvania: PENNSYLVANIA_CITIES,
  'New Jersey': NEW_JERSEY_CITIES,
  Massachusetts: MASSACHUSETTS_CITIES,
  Connecticut: CONNECTICUT_CITIES,
  'Rhode Island': RHODE_ISLAND_CITIES,
  Vermont: VERMONT_CITIES,
  'New Hampshire': NEW_HAMPSHIRE_CITIES,
  Maine: MAINE_CITIES,

  // Midwest
  Illinois: ILLINOIS_CITIES,
  Ohio: OHIO_CITIES,
  Michigan: MICHIGAN_CITIES,
  Wisconsin: WISCONSIN_CITIES,
  Minnesota: MINNESOTA_CITIES,
  Missouri: MISSOURI_CITIES,
  Indiana: INDIANA_CITIES,
  Iowa: IOWA_CITIES,
  Kansas: KANSAS_CITIES,
  Nebraska: NEBRASKA_CITIES,
  'North Dakota': NORTH_DAKOTA_CITIES,
  'South Dakota': SOUTH_DAKOTA_CITIES,

  // Southeast
  Georgia: GEORGIA_CITIES,
  'North Carolina': NORTH_CAROLINA_CITIES,
  'South Carolina': SOUTH_CAROLINA_CITIES,
  Virginia: VIRGINIA_CITIES,
  Tennessee: TENNESSEE_CITIES,
  Kentucky: KENTUCKY_CITIES,
  Alabama: ALABAMA_CITIES,
  Mississippi: MISSISSIPPI_CITIES,
  Louisiana: LOUISIANA_CITIES,
  Arkansas: ARKANSAS_CITIES,
  'West Virginia': WEST_VIRGINIA_CITIES,

  // Southwest & Mountain West
  Arizona: ARIZONA_CITIES,
  'New Mexico': NEW_MEXICO_CITIES,
  Nevada: NEVADA_CITIES,
  Colorado: COLORADO_CITIES,
  Utah: UTAH_CITIES,
  Idaho: IDAHO_CITIES,
  Montana: MONTANA_CITIES,
  Wyoming: WYOMING_CITIES,
  Oklahoma: OKLAHOMA_CITIES,

  // Pacific Northwest & Others
  Washington: WASHINGTON_CITIES,
  Oregon: OREGON_CITIES,
  Alaska: ALASKA_CITIES,
  Hawaii: HAWAII_CITIES,
  Delaware: DELAWARE_CITIES,
  Maryland: MARYLAND_CITIES,
  'District of Columbia': WASHINGTON_DC_CITIES,
};

// Export individual state arrays for direct import
export {
  CALIFORNIA_CITIES,
  TEXAS_CITIES,
  NEW_YORK_CITIES,
  FLORIDA_CITIES,
  PENNSYLVANIA_CITIES,
  NEW_JERSEY_CITIES,
  MASSACHUSETTS_CITIES,
  CONNECTICUT_CITIES,
  RHODE_ISLAND_CITIES,
  VERMONT_CITIES,
  NEW_HAMPSHIRE_CITIES,
  MAINE_CITIES,
  ILLINOIS_CITIES,
  OHIO_CITIES,
  MICHIGAN_CITIES,
  WISCONSIN_CITIES,
  MINNESOTA_CITIES,
  MISSOURI_CITIES,
  INDIANA_CITIES,
  IOWA_CITIES,
  KANSAS_CITIES,
  NEBRASKA_CITIES,
  NORTH_DAKOTA_CITIES,
  SOUTH_DAKOTA_CITIES,
  GEORGIA_CITIES,
  NORTH_CAROLINA_CITIES,
  SOUTH_CAROLINA_CITIES,
  VIRGINIA_CITIES,
  TENNESSEE_CITIES,
  KENTUCKY_CITIES,
  ALABAMA_CITIES,
  MISSISSIPPI_CITIES,
  LOUISIANA_CITIES,
  ARKANSAS_CITIES,
  WEST_VIRGINIA_CITIES,
  ARIZONA_CITIES,
  NEW_MEXICO_CITIES,
  NEVADA_CITIES,
  COLORADO_CITIES,
  UTAH_CITIES,
  IDAHO_CITIES,
  MONTANA_CITIES,
  WYOMING_CITIES,
  OKLAHOMA_CITIES,
  WASHINGTON_CITIES,
  OREGON_CITIES,
  ALASKA_CITIES,
  HAWAII_CITIES,
  DELAWARE_CITIES,
  MARYLAND_CITIES,
  WASHINGTON_DC_CITIES,
};
