// Midwest US cities

// Illinois
export const ILLINOIS_CITIES = [
  'Chicago',
  'Aurora',
  'Naperville',
  'Joliet',
  'Rockford',
  'Springfield',
  'Elgin',
  'Peoria',
  'Champaign',
  'Waukegan',
  'Cicero',
  'Bloomington',
  'Arlington Heights',
  'Evanston',
  'Decatur',
  'Schaumburg',
  'Bolingbrook',
  'Palatine',
  'Skokie',
  'Des Plaines',
  'Orland Park',
  'Tinley Park',
  'Oak Lawn',
  'Berwyn',
  'Mount Prospect',
  'Normal',
  'Wheaton',
  'Hoffman Estates',
  'Oak Park',
  'Downers Grove',
  'Elmhurst',
  'Glenview',
  'DeKalb',
  'Lombard',
  'Moline',
  'Buffalo Grove',
  'Bartlett',
  'Urbana',
  'Quincy',
  'Crystal Lake',
];

// Ohio
export const OHIO_CITIES = [
  'Columbus',
  'Cleveland',
  'Cincinnati',
  'Toledo',
  'Akron',
  'Dayton',
  'Parma',
  'Canton',
  'Youngstown',
  'Lorain',
  'Hamilton',
  'Springfield',
  'Kettering',
  'Elyria',
  'Lakewood',
  'Cuyahoga Falls',
  'Middletown',
  'Euclid',
  'Newark',
  'Mansfield',
  'Mentor',
  'Beavercreek',
  'Cleveland Heights',
  'Strongsville',
  'Dublin',
  'Fairfield',
  'Findlay',
  'Warren',
  'Lancaster',
  'Lima',
  'Huber Heights',
  'Westerville',
  'Marion',
  'Grove City',
  'Bowling Green',
];

// Michigan
export const MICHIGAN_CITIES = [
  'Detroit',
  'Grand Rapids',
  'Warren',
  'Sterling Heights',
  'Ann Arbor',
  'Lansing',
  'Flint',
  'Dearborn',
  'Livonia',
  'Troy',
  'Westland',
  'Farmington Hills',
  'Kalamazoo',
  'Wyoming',
  'Southfield',
  'Rochester Hills',
  'Taylor',
  'Pontiac',
  'St. Clair Shores',
  'Royal Oak',
  'Novi',
  'Dearborn Heights',
  'Battle Creek',
  'Saginaw',
  'Kentwood',
  'East Lansing',
  'Roseville',
  'Portage',
  'Midland',
  'Lincoln Park',
  'Muskegon',
];

// Wisconsin
export const WISCONSIN_CITIES = [
  'Milwaukee',
  'Madison',
  'Green Bay',
  'Kenosha',
  'Racine',
  'Appleton',
  'Waukesha',
  'Eau Claire',
  'Oshkosh',
  'Janesville',
  'West Allis',
  'La Crosse',
  'Sheboygan',
  'Wauwatosa',
  'Fond du Lac',
  'New Berlin',
  'Wausau',
  'Brookfield',
  'Greenfield',
  'Beloit',
  'Franklin',
  'Oak Creek',
  'Manitowoc',
  'West Bend',
  'Sun Prairie',
  'Superior',
  'Stevens Point',
  'Neenah',
  'Mequon',
  'Fitchburg',
];

// Minnesota
export const MINNESOTA_CITIES = [
  'Minneapolis',
  'St. Paul',
  'Rochester',
  'Duluth',
  'Bloomington',
  'Brooklyn Park',
  'Plymouth',
  'St. Cloud',
  'Eagan',
  'Woodbury',
  'Maple Grove',
  'Eden Prairie',
  'Coon Rapids',
  'Burnsville',
  'Blaine',
  'Lakeville',
  'Minnetonka',
  'Apple Valley',
  'Edina',
  'St. Louis Park',
  'Mankato',
  'Maplewood',
  'Moorhead',
  'Shakopee',
  'Cottage Grove',
  'Richfield',
  'Roseville',
  'Inver Grove Heights',
  'Brooklyn Center',
  'Andover',
];

// Missouri
export const MISSOURI_CITIES = [
  'Kansas City',
  'St. Louis',
  'Springfield',
  'Columbia',
  'Independence',
  "Lee's Summit",
  "O'Fallon",
  'St. Joseph',
  'St. Charles',
  'St. Peters',
  'Blue Springs',
  'Florissant',
  'Joplin',
  'Chesterfield',
  'Jefferson City',
  'Cape Girardeau',
  'Wildwood',
  'University City',
  'Ballwin',
  'Raytown',
  'Liberty',
  'Wentzville',
  'Mehlville',
  'Kirkwood',
  'Maryland Heights',
  'Gladstone',
  'Grandview',
  'Belton',
  'Hazelwood',
  'Webster Groves',
];

// Indiana
export const INDIANA_CITIES = [
  'Indianapolis',
  'Fort Wayne',
  'Evansville',
  'South Bend',
  'Carmel',
  'Fishers',
  'Bloomington',
  'Hammond',
  'Gary',
  'Muncie',
  'Lafayette',
  'Terre Haute',
  'Kokomo',
  'Anderson',
  'Noblesville',
  'Greenwood',
  'Elkhart',
  'Mishawaka',
  'Lawrence',
  'Jeffersonville',
  'Columbus',
  'Portage',
  'New Albany',
  'Richmond',
  'Westfield',
  'Valparaiso',
  'Goshen',
  'Michigan City',
  'Marion',
  'West Lafayette',
];

// Iowa
export const IOWA_CITIES = [
  'Des Moines',
  'Cedar Rapids',
  'Davenport',
  'Sioux City',
  'Iowa City',
  'Waterloo',
  'Council Bluffs',
  'Ames',
  'West Des Moines',
  'Dubuque',
  'Ankeny',
  'Urbandale',
  'Cedar Falls',
  'Marion',
  'Bettendorf',
  'Mason City',
  'Marshalltown',
  'Clinton',
  'Burlington',
  'Ottumwa',
];

// Kansas
export const KANSAS_CITIES = [
  'Wichita',
  'Overland Park',
  'Kansas City',
  'Olathe',
  'Topeka',
  'Lawrence',
  'Shawnee',
  'Manhattan',
  'Lenexa',
  'Salina',
  'Hutchinson',
  'Leavenworth',
  'Leawood',
  'Dodge City',
  'Garden City',
  'Junction City',
  'Emporia',
  'Derby',
  'Prairie Village',
  'Hays',
];

// Nebraska
export const NEBRASKA_CITIES = [
  'Omaha',
  'Lincoln',
  'Bellevue',
  'Grand Island',
  'Kearney',
  'Fremont',
  'Hastings',
  'North Platte',
  'Norfolk',
  'Columbus',
  'Papillion',
  'La Vista',
  'Scottsbluff',
  'South Sioux City',
  'Beatrice',
  'Chalco',
  'Lexington',
  'Gering',
  'Alliance',
  'Blair',
];

// North Dakota
export const NORTH_DAKOTA_CITIES = [
  'Fargo',
  'Bismarck',
  'Grand Forks',
  'Minot',
  'West Fargo',
  'Williston',
  'Dickinson',
  'Mandan',
  'Jamestown',
  'Wahpeton',
];

// South Dakota
export const SOUTH_DAKOTA_CITIES = [
  'Sioux Falls',
  'Rapid City',
  'Aberdeen',
  'Brookings',
  'Watertown',
  'Mitchell',
  'Yankton',
  'Pierre',
  'Huron',
  'Spearfish',
];
