// New York cities - comprehensive list

export const NEW_YORK_CITIES = [
  // New York City Boroughs
  'New York City',
  'Brooklyn',
  'Queens',
  'Manhattan',
  'Bronx',
  'Staten Island',

  // Long Island
  'Hempstead',
  'Islip',
  'Brookhaven',
  'Oyster Bay',
  'North Hempstead',
  'Babylon',
  'Huntington',
  'Smithtown',
  'Riverhead',
  'Southampton',
  'East Hampton',
  'Shelter Island',
  'Freeport',
  'Long Beach',
  'Glen Cove',
  'Rockville Centre',
  'Garden City',
  'Mineola',
  'Hicksville',
  'Levittown',
  'Massapequa',
  'Plainview',
  'Westbury',
  'Port Washington',
  'Great Neck',
  'Manhasset',

  // Hudson Valley
  'Yonkers',
  'Mount Vernon',
  'New Rochelle',
  'White Plains',
  'Port Chester',
  'Rye',
  'Scarsdale',
  'Mamaroneck',
  'Harrison',
  'Peekskill',
  'Ossining',
  'Tarrytown',
  'Sleepy Hollow',
  'Hastings-on-Hudson',
  'Dobbs Ferry',
  'Irvington',
  'Croton-on-Hudson',
  'Poughkeepsie',
  'Newburgh',
  'Beacon',
  'Kingston',
  'Middletown',
  'Monticello',
  'Liberty',

  // Capital Region
  'Albany',
  'Schenectady',
  'Troy',
  'Saratoga Springs',
  'Cohoes',
  'Watervliet',
  'Rensselaer',
  'Glens Falls',
  'Amsterdam',
  'Gloversville',
  'Johnstown',

  // Central New York
  'Syracuse',
  'Utica',
  'Rome',
  'Oneida',
  'Auburn',
  'Fulton',
  'Oswego',
  'Cortland',
  'Ithaca',
  'Elmira',
  'Corning',
  'Binghamton',
  'Endicott',
  'Johnson City',
  'Vestal',

  // Western New York
  'Buffalo',
  'Rochester',
  'Niagara Falls',
  'Cheektowaga',
  'West Seneca',
  'Amherst',
  'Tonawanda',
  'North Tonawanda',
  'Lackawanna',
  'Kenmore',
  'Lockport',
  'Jamestown',
  'Dunkirk',
  'Batavia',
  'Canandaigua',
  'Geneva',
  'Watertown',
  'Ogdensburg',
  'Plattsburgh',
  'Massena',
  'Malone',

  // Finger Lakes
  'Ithaca',
  'Elmira',
  'Corning',
  'Canandaigua',
  'Geneva',
  'Watkins Glen',
  'Penn Yan',
  'Seneca Falls',
];
