// Northeast US cities (excluding NY which has its own file)

// Pennsylvania
export const PENNSYLVANIA_CITIES = [
  'Philadelphia',
  'Pittsburgh',
  'Allentown',
  'Erie',
  'Reading',
  'Scranton',
  'Bethlehem',
  'Lancaster',
  'Harrisburg',
  'Altoona',
  'York',
  'State College',
  'Wilkes-Barre',
  'Chester',
  'Williamsport',
  'Easton',
  'Lebanon',
  'Hazleton',
  'New Castle',
  'Johnstown',
  'McKeesport',
  'Hermitage',
  'Greensburg',
  'Pottstown',
  'Monroeville',
  'Plum',
  'Norristown',
  'West Chester',
  'King of Prussia',
];

// New Jersey
export const NEW_JERSEY_CITIES = [
  'Newark',
  'Jersey City',
  'Paterson',
  'Elizabeth',
  'Edison',
  'Woodbridge',
  'Lakewood',
  'Toms River',
  'Hamilton',
  'Trenton',
  'Clifton',
  'Camden',
  'Brick',
  'Cherry Hill',
  'Passaic',
  'Union City',
  'Old Bridge',
  'Gloucester Township',
  'East Orange',
  'Bayonne',
  'Franklin Township',
  'North Bergen',
  'Vineland',
  'Union Township',
  'Piscataway',
  'New Brunswick',
  'Jackson',
  'Wayne',
  'Irvington',
  'Parsippany-Troy Hills',
  'Howell',
  'Perth Amboy',
  'Hoboken',
  'Plainfield',
  'West New York',
  'Washington Township',
  'East Brunswick',
  'Bloomfield',
  'West Orange',
];

// Massachusetts
export const MASSACHUSETTS_CITIES = [
  'Boston',
  'Worcester',
  'Springfield',
  'Cambridge',
  'Lowell',
  'Brockton',
  'Quincy',
  'Lynn',
  'New Bedford',
  'Fall River',
  'Newton',
  'Lawrence',
  'Somerville',
  'Framingham',
  'Haverhill',
  'Waltham',
  'Malden',
  'Brookline',
  'Plymouth',
  'Medford',
  'Taunton',
  'Chicopee',
  'Weymouth',
  'Revere',
  'Peabody',
  'Methuen',
  'Barnstable',
  'Pittsfield',
  'Attleboro',
  'Salem',
  'Westfield',
  'Leominster',
  'Beverly',
  'Holyoke',
  'Fitchburg',
  'Woburn',
  'Northampton',
  'Gloucester',
  'Amherst',
];

// Connecticut
export const CONNECTICUT_CITIES = [
  'Bridgeport',
  'New Haven',
  'Stamford',
  'Hartford',
  'Waterbury',
  'Norwalk',
  'Danbury',
  'New Britain',
  'West Hartford',
  'Bristol',
  'Meriden',
  'Milford',
  'Middletown',
  'Norwich',
  'Shelton',
  'Torrington',
  'Stratford',
  'New London',
  'Groton',
  'Wallingford',
  'Hamden',
  'East Hartford',
  'Manchester',
  'West Haven',
  'Fairfield',
  'Trumbull',
  'Mansfield',
  'Glastonbury',
];

// Rhode Island
export const RHODE_ISLAND_CITIES = [
  'Providence',
  'Warwick',
  'Cranston',
  'Pawtucket',
  'East Providence',
  'Woonsocket',
  'Coventry',
  'Cumberland',
  'North Providence',
  'South Kingstown',
  'West Warwick',
  'Johnston',
  'North Kingstown',
  'Newport',
  'Bristol',
  'Smithfield',
  'Middletown',
  'Barrington',
  'Portsmouth',
  'Westerly',
];

// Vermont
export const VERMONT_CITIES = [
  'Burlington',
  'South Burlington',
  'Rutland',
  'Essex',
  'Colchester',
  'Bennington',
  'Brattleboro',
  'Hartford',
  'Milton',
  'Barre',
  'Williston',
  'St. Albans',
  'Montpelier',
  'Winooski',
  'Springfield',
  'St. Johnsbury',
];

// New Hampshire
export const NEW_HAMPSHIRE_CITIES = [
  'Manchester',
  'Nashua',
  'Concord',
  'Derry',
  'Dover',
  'Rochester',
  'Salem',
  'Merrimack',
  'Londonderry',
  'Hudson',
  'Keene',
  'Bedford',
  'Portsmouth',
  'Goffstown',
  'Laconia',
  'Hampton',
  'Milford',
  'Durham',
  'Exeter',
  'Windham',
];

// Maine
export const MAINE_CITIES = [
  'Portland',
  'Lewiston',
  'Bangor',
  'South Portland',
  'Auburn',
  'Biddeford',
  'Sanford',
  'Saco',
  'Augusta',
  'Westbrook',
  'Waterville',
  'Presque Isle',
  'Bath',
  'Brunswick',
  'Scarborough',
  'Gorham',
  'Brewer',
  'Orono',
  'Old Town',
  'Belfast',
];
