// Pacific Northwest and Alaska/Hawaii cities

// Washington
export const WASHINGTON_CITIES = [
  'Seattle',
  'Spokane',
  'Tacoma',
  'Vancouver',
  'Bellevue',
  'Kent',
  'Everett',
  'Renton',
  'Spokane Valley',
  'Federal Way',
  'Yakima',
  'Bellingham',
  'Kennewick',
  'Auburn',
  'Pasco',
  'Marysville',
  'Lakewood',
  'Redmond',
  'Shoreline',
  'Richland',
  'Kirkland',
  'Burien',
  'Sammamish',
  'Olympia',
  'Lacey',
  'Edmonds',
  'Bremerton',
  'Puyallup',
  'Bothell',
  'South Hill',
  'Wenatchee',
  'Mount Vernon',
  'Walla Walla',
  'Pullman',
  'Des Moines',
  'University Place',
  'Longview',
  'Issaquah',
  'Lynnwood',
  'SeaTac',
];

// Oregon
export const OREGON_CITIES = [
  'Portland',
  'Salem',
  'Eugene',
  'Gresham',
  'Hillsboro',
  'Beaverton',
  'Bend',
  'Medford',
  'Springfield',
  'Corvallis',
  'Albany',
  'Tigard',
  'Lake Oswego',
  'Keizer',
  'Grants Pass',
  'Oregon City',
  'McMinnville',
  'Redmond',
  'Tualatin',
  'West Linn',
  'Woodburn',
  'Forest Grove',
  'Newberg',
  'Wilsonville',
  'Roseburg',
  'Klamath Falls',
  'Ashland',
  'Milwaukie',
  'Sherwood',
  'Happy Valley',
];

// Alaska
export const ALASKA_CITIES = [
  'Anchorage',
  'Fairbanks',
  'Juneau',
  'Sitka',
  'Ketchikan',
  'Wasilla',
  'Kenai',
  'Kodiak',
  'Bethel',
  'Palmer',
  'Homer',
  'Unalaska',
  'Soldotna',
  'Barrow',
  'Nome',
  'Kotzebue',
  'Valdez',
  'Seward',
  'Petersburg',
  'Wrangell',
];

// Hawaii
export const HAWAII_CITIES = [
  'Honolulu',
  'Pearl City',
  'Hilo',
  'Kailua',
  'Waipahu',
  'Kaneohe',
  'Mililani Town',
  'Kahului',
  'Ewa Gentry',
  'Mililani Mauka',
  'Kihei',
  'Makakilo',
  'Wahiawa',
  'Ewa Beach',
  'Royal Kunia',
  'Kapolei',
  'Waianae',
  'Wailuku',
  'Nanakuli',
  'Schofield Barracks',
];

// Delaware
export const DELAWARE_CITIES = [
  'Wilmington',
  'Dover',
  'Newark',
  'Middletown',
  'Smyrna',
  'Milford',
  'Seaford',
  'Georgetown',
  'Elsmere',
  'New Castle',
  'Millsboro',
  'Laurel',
  'Harrington',
  'Camden',
  'Clayton',
  'Lewes',
  'Rehoboth Beach',
  'Bridgeville',
  'Delmar',
  'Selbyville',
];

// Maryland
export const MARYLAND_CITIES = [
  'Baltimore',
  'Columbia',
  'Germantown',
  'Silver Spring',
  'Waldorf',
  'Glen Burnie',
  'Ellicott City',
  'Frederick',
  'Dundalk',
  'Rockville',
  'Bethesda',
  'Gaithersburg',
  'Bowie',
  'Hagerstown',
  'Annapolis',
  'Towson',
  'Salisbury',
  'Wheaton',
  'Aspen Hill',
  'Severn',
  'College Park',
  'North Bethesda',
  'Potomac',
  'Clinton',
  'Chillum',
  'South Laurel',
  'Catonsville',
  'Olney',
  'Parkville',
  'Woodlawn',
];

// Washington DC
export const WASHINGTON_DC_CITIES = ['Washington'];
