// Southwest and Mountain West US cities

// Arizona
export const ARIZONA_CITIES = [
  'Phoenix',
  'Tucson',
  'Mesa',
  'Chandler',
  'Scottsdale',
  'Glendale',
  'Gilbert',
  'Tempe',
  'Peoria',
  'Surprise',
  'Yuma',
  'Avondale',
  'Flagstaff',
  'Goodyear',
  'Buckeye',
  'Lake Havasu City',
  'Casa Grande',
  'Sierra Vista',
  'Maricopa',
  'Oro Valley',
  'Prescott',
  'Bullhead City',
  'Prescott Valley',
  'Marana',
  'Apache Junction',
  'Kingman',
  'Queen Creek',
  'Florence',
  'San Luis',
  'Sahuarita',
];

// New Mexico
export const NEW_MEXICO_CITIES = [
  'Albuquerque',
  'Las Cruces',
  'Rio Rancho',
  'Santa Fe',
  'Roswell',
  'Farmington',
  'Clovis',
  'Hobbs',
  'Alamogordo',
  'Carlsbad',
  'Gallup',
  'Deming',
  'Los Lunas',
  'Chaparral',
  'Sunland Park',
  'Las Vegas',
  'Portales',
  'Los Alamos',
  'North Valley',
  'South Valley',
];

// Nevada
export const NEVADA_CITIES = [
  'Las Vegas',
  'Henderson',
  'Reno',
  'North Las Vegas',
  'Sparks',
  'Carson City',
  'Fernley',
  'Elko',
  'Mesquite',
  'Boulder City',
  'Fallon',
  'Winnemucca',
  'West Wendover',
  'Ely',
  'Yerington',
  'Carlin',
  'Lovelock',
  'Wells',
  'Battle Mountain',
  'Tonopah',
];

// Colorado
export const COLORADO_CITIES = [
  'Denver',
  'Colorado Springs',
  'Aurora',
  'Fort Collins',
  'Lakewood',
  'Thornton',
  'Arvada',
  'Westminster',
  'Pueblo',
  'Centennial',
  'Boulder',
  'Greeley',
  'Longmont',
  'Loveland',
  'Grand Junction',
  'Broomfield',
  'Castle Rock',
  'Commerce City',
  'Parker',
  'Littleton',
  'Northglenn',
  'Brighton',
  'Englewood',
  'Wheat Ridge',
  'Windsor',
  'Erie',
  'Evans',
  'Fort Morgan',
  'Montrose',
  'Durango',
];

// Utah
export const UTAH_CITIES = [
  'Salt Lake City',
  'West Valley City',
  'Provo',
  'West Jordan',
  'Orem',
  'Sandy',
  'Ogden',
  'St. George',
  'Layton',
  'Taylorsville',
  'South Jordan',
  'Lehi',
  'Logan',
  'Murray',
  'Draper',
  'Bountiful',
  'Riverton',
  'Roy',
  'Spanish Fork',
  'Pleasant Grove',
  'Kearns',
  'Tooele',
  'Cottonwood Heights',
  'Springville',
  'Cedar City',
  'Herriman',
  'Eagle Mountain',
  'Saratoga Springs',
  'Magna',
  'Clearfield',
];

// Idaho
export const IDAHO_CITIES = [
  'Boise',
  'Meridian',
  'Nampa',
  'Idaho Falls',
  'Pocatello',
  'Caldwell',
  "Coeur d'Alene",
  'Twin Falls',
  'Post Falls',
  'Lewiston',
  'Rexburg',
  'Eagle',
  'Moscow',
  'Kuna',
  'Ammon',
  'Mountain Home',
  'Chubbuck',
  'Blackfoot',
  'Garden City',
  'Star',
];

// Montana
export const MONTANA_CITIES = [
  'Billings',
  'Missoula',
  'Great Falls',
  'Bozeman',
  'Butte',
  'Helena',
  'Kalispell',
  'Havre',
  'Anaconda',
  'Miles City',
  'Belgrade',
  'Livingston',
  'Laurel',
  'Whitefish',
  'Lewistown',
  'Sidney',
  'Glendive',
  'Columbia Falls',
  'Polson',
  'Hamilton',
];

// Wyoming
export const WYOMING_CITIES = [
  'Cheyenne',
  'Casper',
  'Laramie',
  'Gillette',
  'Rock Springs',
  'Sheridan',
  'Green River',
  'Evanston',
  'Riverton',
  'Jackson',
  'Cody',
  'Rawlins',
  'Lander',
  'Torrington',
  'Powell',
  'Douglas',
  'Worland',
  'Buffalo',
  'Wheatland',
  'Thermopolis',
];

// Oklahoma
export const OKLAHOMA_CITIES = [
  'Oklahoma City',
  'Tulsa',
  'Norman',
  'Broken Arrow',
  'Edmond',
  'Lawton',
  'Moore',
  'Midwest City',
  'Enid',
  'Stillwater',
  'Muskogee',
  'Bartlesville',
  'Owasso',
  'Shawnee',
  'Yukon',
  'Ardmore',
  'Ponca City',
  'Duncan',
  'Del City',
  'Sapulpa',
];
