// Southeast US cities (excluding Florida which has its own file)

// Georgia
export const GEORGIA_CITIES = [
  'Atlanta',
  'Augusta',
  'Columbus',
  'Macon',
  'Savannah',
  'Athens',
  'Sandy Springs',
  'Roswell',
  'Johns Creek',
  'Albany',
  'Warner Robins',
  'Alpharetta',
  'Marietta',
  'Valdosta',
  'Smyrna',
  'Dunwoody',
  'Rome',
  'East Point',
  'Milton',
  'Peachtree Corners',
  'Gainesville',
  'Hinesville',
  'Newnan',
  'Dalton',
  'Brookhaven',
  'LaGrange',
  'Kennesaw',
  'Douglasville',
  'Lawrenceville',
  'McDonough',
];

// North Carolina
export const NORTH_CAROLINA_CITIES = [
  'Charlotte',
  'Raleigh',
  'Greensboro',
  'Durham',
  'Winston-Salem',
  'Fayetteville',
  'Cary',
  'Wilmington',
  'High Point',
  'Concord',
  'Asheville',
  'Greenville',
  'Jacksonville',
  'Chapel Hill',
  'Huntersville',
  'Burlington',
  'Wilson',
  'Kannapolis',
  'Apex',
  'Hickory',
  'Gastonia',
  'Rocky Mount',
  'Mooresville',
  'Salisbury',
  'Holly Springs',
  'Matthews',
  'New Bern',
  'Wake Forest',
  'Indian Trail',
  'Cornelius',
];

// South Carolina
export const SOUTH_CAROLINA_CITIES = [
  'Columbia',
  'Charleston',
  'North Charleston',
  'Mount Pleasant',
  'Rock Hill',
  'Greenville',
  'Summerville',
  'Sumter',
  'Goose Creek',
  'Hilton Head Island',
  'Florence',
  'Spartanburg',
  'Myrtle Beach',
  'Aiken',
  'Anderson',
  'Greer',
  'Mauldin',
  'Greenwood',
  'North Augusta',
  'Easley',
];

// Virginia
export const VIRGINIA_CITIES = [
  'Virginia Beach',
  'Norfolk',
  'Chesapeake',
  'Richmond',
  'Newport News',
  'Alexandria',
  'Hampton',
  'Roanoke',
  'Portsmouth',
  'Suffolk',
  'Lynchburg',
  'Harrisonburg',
  'Leesburg',
  'Charlottesville',
  'Danville',
  'Blacksburg',
  'Manassas',
  'Petersburg',
  'Fredericksburg',
  'Winchester',
  'Salem',
  'Staunton',
  'Christiansburg',
  'Centreville',
  'Herndon',
  'Vienna',
  'Ashburn',
  'Sterling',
  'Reston',
  'McLean',
];

// Tennessee
export const TENNESSEE_CITIES = [
  'Nashville',
  'Memphis',
  'Knoxville',
  'Chattanooga',
  'Clarksville',
  'Murfreesboro',
  'Franklin',
  'Jackson',
  'Johnson City',
  'Bartlett',
  'Hendersonville',
  'Kingsport',
  'Collierville',
  'Smyrna',
  'Cleveland',
  'Brentwood',
  'Germantown',
  'Columbia',
  'Spring Hill',
  'La Vergne',
];

// Kentucky
export const KENTUCKY_CITIES = [
  'Louisville',
  'Lexington',
  'Bowling Green',
  'Owensboro',
  'Covington',
  'Richmond',
  'Georgetown',
  'Florence',
  'Elizabethtown',
  'Hopkinsville',
  'Nicholasville',
  'Henderson',
  'Jeffersontown',
  'Frankfort',
  'Paducah',
  'Independence',
  'Radcliff',
  'Ashland',
  'Madisonville',
  'Winchester',
];

// Alabama
export const ALABAMA_CITIES = [
  'Birmingham',
  'Montgomery',
  'Mobile',
  'Huntsville',
  'Tuscaloosa',
  'Hoover',
  'Dothan',
  'Auburn',
  'Decatur',
  'Madison',
  'Florence',
  'Gadsden',
  'Vestavia Hills',
  'Prattville',
  'Phenix City',
  'Alabaster',
  'Bessemer',
  'Enterprise',
  'Opelika',
  'Homewood',
];

// Mississippi
export const MISSISSIPPI_CITIES = [
  'Jackson',
  'Gulfport',
  'Southaven',
  'Hattiesburg',
  'Biloxi',
  'Meridian',
  'Tupelo',
  'Greenville',
  'Olive Branch',
  'Horn Lake',
  'Clinton',
  'Pearl',
  'Madison',
  'Ridgeland',
  'Starkville',
  'Columbus',
  'Vicksburg',
  'Pascagoula',
  'Brandon',
  'Oxford',
];

// Louisiana
export const LOUISIANA_CITIES = [
  'New Orleans',
  'Baton Rouge',
  'Shreveport',
  'Lafayette',
  'Lake Charles',
  'Kenner',
  'Bossier City',
  'Monroe',
  'Alexandria',
  'Houma',
  'Prairieville',
  'Central',
  'New Iberia',
  'Laplace',
  'Slidell',
  'Ruston',
  'Hammond',
  'Sulphur',
  'Zachary',
  'Natchitoches',
];

// Arkansas
export const ARKANSAS_CITIES = [
  'Little Rock',
  'Fort Smith',
  'Fayetteville',
  'Springdale',
  'Jonesboro',
  'North Little Rock',
  'Conway',
  'Rogers',
  'Pine Bluff',
  'Bentonville',
  'Hot Springs',
  'Benton',
  'Sherwood',
  'Texarkana',
  'Russellville',
  'Jacksonville',
  'Bella Vista',
  'Paragould',
  'Cabot',
  'Searcy',
];

// West Virginia
export const WEST_VIRGINIA_CITIES = [
  'Charleston',
  'Huntington',
  'Morgantown',
  'Parkersburg',
  'Wheeling',
  'Weirton',
  'Fairmont',
  'Beckley',
  'Martinsburg',
  'Clarksburg',
  'South Charleston',
  'St. Albans',
  'Vienna',
  'Bluefield',
  'Teays Valley',
  'Cross Lanes',
  'Moundsville',
  'Dunbar',
  'Hurricane',
  'Bridgeport',
];
