// Texas cities - comprehensive list

export const TEXAS_CITIES = [
  // Major Cities
  'Houston',
  'San Antonio',
  'Dallas',
  'Austin',
  'Fort Worth',
  'El Paso',
  'Arlington',
  'Corpus Christi',
  'Plano',
  'Lubbock',

  // Houston Metro
  'Pasadena',
  'Pearland',
  'League City',
  'Sugar Land',
  'Missouri City',
  'The Woodlands',
  'Conroe',
  'Baytown',
  'Texas City',
  'Galveston',
  'Friendswood',
  'La Porte',
  'Deer Park',
  'Katy',
  'Humble',
  'Spring',
  'Rosenberg',
  'Richmond',
  'Angleton',
  'Alvin',
  'Channelview',

  // Dallas-Fort Worth Metroplex
  'Dallas',
  'Fort Worth',
  'Arlington',
  'Plano',
  'Irving',
  'Garland',
  'Grand Prairie',
  'McKinney',
  'Frisco',
  'Carrollton',
  'Denton',
  'Richardson',
  'Lewisville',
  'Allen',
  'Flower Mound',
  'Mesquite',
  'Wichita Falls',
  'Rowlett',
  'Grapevine',
  'Euless',
  'Bedford',
  'Coppell',
  'Hurst',
  'Duncanville',
  'The Colony',
  'Farmers Branch',
  'Cedar Hill',
  'Desoto',
  'Wylie',
  'Rockwall',
  'Mansfield',
  'Burleson',
  'Cleburne',

  // San Antonio Metro
  'San Antonio',
  'New Braunfels',
  'San Marcos',
  'Seguin',
  'Schertz',
  'Cibolo',
  'Universal City',
  'Converse',
  'Live Oak',
  'Selma',
  'Boerne',
  'Kerrville',

  // Austin Metro
  'Austin',
  'Round Rock',
  'Georgetown',
  'Cedar Park',
  'Pflugerville',
  'Leander',
  'Kyle',
  'Buda',
  'Bastrop',
  'Lockhart',
  'Marble Falls',
  'Dripping Springs',

  // El Paso Region
  'El Paso',
  'Socorro',
  'Horizon City',

  // Corpus Christi Region
  'Corpus Christi',
  'Port Arthur',
  'Beaumont',
  'Orange',
  'Kingsville',
  'Portland',
  'Rockport',
  'Aransas Pass',

  // Rio Grande Valley
  'Brownsville',
  'McAllen',
  'Edinburg',
  'Mission',
  'Pharr',
  'Harlingen',
  'Laredo',
  'Weslaco',
  'San Juan',
  'Alamo',
  'Donna',
  'Mercedes',
  'Rio Grande City',
  'Raymondville',

  // West Texas
  'Lubbock',
  'Amarillo',
  'Midland',
  'Odessa',
  'Abilene',
  'San Angelo',
  'Big Spring',
  'Plainview',
  'Levelland',

  // East Texas
  'Tyler',
  'Longview',
  'Texarkana',
  'Marshall',
  'Palestine',
  'Jacksonville',
  'Athens',
  'Nacogdoches',
  'Lufkin',

  // Central Texas
  'Temple',
  'Killeen',
  'Waco',
  'Bryan',
  'College Station',
  'Harker Heights',
  'Copperas Cove',
  'Belton',

  // South Texas
  'Victoria',
  'Del Rio',
  'Eagle Pass',
  'Uvalde',
  'Alice',
  'Beeville',
];
