// Major cities by state/province

import type { StateProvinceName } from './types';

export const MAJOR_CITIES: { [key in StateProvinceName]?: string[] } = {
  // US States
  California: [
    'Los Angeles',
    'San Francisco',
    'San Diego',
    'San Jose',
    'Fresno',
    'Sacramento',
    'Long Beach',
    'Oakland',
    'Bakersfield',
    'Anaheim',
  ],
  Texas: [
    'Houston',
    'San Antonio',
    'Dallas',
    'Austin',
    'Fort Worth',
    'El Paso',
    'Arlington',
    'Corpus Christi',
    'Plano',
    'Lubbock',
  ],
  'New York': [
    'New York City',
    'Buffalo',
    'Rochester',
    'Yonkers',
    'Syracuse',
    'Albany',
    'New Rochelle',
    'Mount Vernon',
    'Schenectady',
    'Utica',
  ],
  Florida: [
    'Jacksonville',
    'Miami',
    'Tampa',
    'Orlando',
    'St. Petersburg',
    'Hialeah',
    'Tallahassee',
    'Fort Lauderdale',
    'Port St. Lucie',
    'Cape Coral',
  ],
  Illinois: [
    'Chicago',
    'Aurora',
    'Rockford',
    'Joliet',
    'Naperville',
    'Springfield',
    'Peoria',
    'Elgin',
    'Waukegan',
    'Cicero',
  ],

  // Canadian Provinces
  Ontario: [
    'Toronto',
    'Ottawa',
    'Mississauga',
    'Brampton',
    'Hamilton',
    'London',
    'Markham',
    'Vaughan',
    'Kitchener',
    'Windsor',
  ],
  Quebec: [
    'Montreal',
    'Quebec City',
    'Laval',
    'Gatineau',
    'Longueuil',
    'Sherbrooke',
    'Saguenay',
    'Levis',
    'Trois-Rivieres',
    'Terrebonne',
  ],
  'British Columbia': [
    'Vancouver',
    'Surrey',
    'Burnaby',
    'Richmond',
    'Abbotsford',
    'Coquitlam',
    'Saanich',
    'Delta',
    'Kelowna',
    'Langley',
  ],
  Alberta: [
    'Calgary',
    'Edmonton',
    'Red Deer',
    'Lethbridge',
    'St. Albert',
    'Medicine Hat',
    'Grande Prairie',
    'Airdrie',
    'Spruce Grove',
    'Leduc',
  ],

  // Mexican States
  Jalisco: [
    'Guadalajara',
    'Zapopan',
    'Tlaquepaque',
    'Tonala',
    'Puerto Vallarta',
    'Lagos de Moreno',
    'Ocotlan',
    'Tepatitlan',
    'Arandas',
    'San Juan de los Lagos',
  ],
  Mexico: [
    'Ecatepec',
    'Nezahualcoyotl',
    'Naucalpan',
    'Tlalnepantla',
    'Chimalhuacan',
    'Atizapan',
    'Cuautitlan Izcalli',
    'Tultitlan',
    'Ixtapaluca',
    'Nicolas Romero',
  ],
  'Nuevo Leon': [
    'Monterrey',
    'Guadalupe',
    'Apodaca',
    'San Nicolas de los Garza',
    'General Escobedo',
    'Santa Catarina',
    'Juarez',
    'Garcia',
    'Salinas Victoria',
    'Cadereyta Jimenez',
  ],
};
