// US States and territories

import type { StateProvince } from './types';

export const US_STATES: StateProvince[] = [
  { value: 'Alabama', label: 'Alabama', code: 'AL', country: 'United States' },
  { value: 'Alaska', label: 'Alaska', code: 'AK', country: 'United States' },
  { value: 'Arizona', label: 'Arizona', code: 'AZ', country: 'United States' },
  {
    value: 'Arkansas',
    label: 'Arkansas',
    code: 'AR',
    country: 'United States',
  },
  {
    value: 'California',
    label: 'California',
    code: 'CA',
    country: 'United States',
  },
  {
    value: 'Colorado',
    label: 'Colorado',
    code: 'CO',
    country: 'United States',
  },
  {
    value: 'Connecticut',
    label: 'Connecticut',
    code: 'CT',
    country: 'United States',
  },
  {
    value: 'Delaware',
    label: 'Delaware',
    code: 'DE',
    country: 'United States',
  },
  { value: 'Florida', label: 'Florida', code: 'FL', country: 'United States' },
  { value: 'Georgia', label: 'Georgia', code: 'GA', country: 'United States' },
  { value: 'Hawaii', label: 'Hawaii', code: 'HI', country: 'United States' },
  { value: 'Idaho', label: 'Idaho', code: 'ID', country: 'United States' },
  {
    value: 'Illinois',
    label: 'Illinois',
    code: 'IL',
    country: 'United States',
  },
  { value: 'Indiana', label: 'Indiana', code: 'IN', country: 'United States' },
  { value: 'Iowa', label: 'Iowa', code: 'IA', country: 'United States' },
  { value: 'Kansas', label: 'Kansas', code: 'KS', country: 'United States' },
  {
    value: 'Kentucky',
    label: 'Kentucky',
    code: 'KY',
    country: 'United States',
  },
  {
    value: 'Louisiana',
    label: 'Louisiana',
    code: 'LA',
    country: 'United States',
  },
  { value: 'Maine', label: 'Maine', code: 'ME', country: 'United States' },
  {
    value: 'Maryland',
    label: 'Maryland',
    code: 'MD',
    country: 'United States',
  },
  {
    value: 'Massachusetts',
    label: 'Massachusetts',
    code: 'MA',
    country: 'United States',
  },
  {
    value: 'Michigan',
    label: 'Michigan',
    code: 'MI',
    country: 'United States',
  },
  {
    value: 'Minnesota',
    label: 'Minnesota',
    code: 'MN',
    country: 'United States',
  },
  {
    value: 'Mississippi',
    label: 'Mississippi',
    code: 'MS',
    country: 'United States',
  },
  {
    value: 'Missouri',
    label: 'Missouri',
    code: 'MO',
    country: 'United States',
  },
  { value: 'Montana', label: 'Montana', code: 'MT', country: 'United States' },
  {
    value: 'Nebraska',
    label: 'Nebraska',
    code: 'NE',
    country: 'United States',
  },
  { value: 'Nevada', label: 'Nevada', code: 'NV', country: 'United States' },
  {
    value: 'New Hampshire',
    label: 'New Hampshire',
    code: 'NH',
    country: 'United States',
  },
  {
    value: 'New Jersey',
    label: 'New Jersey',
    code: 'NJ',
    country: 'United States',
  },
  {
    value: 'New Mexico',
    label: 'New Mexico',
    code: 'NM',
    country: 'United States',
  },
  {
    value: 'New York',
    label: 'New York',
    code: 'NY',
    country: 'United States',
  },
  {
    value: 'North Carolina',
    label: 'North Carolina',
    code: 'NC',
    country: 'United States',
  },
  {
    value: 'North Dakota',
    label: 'North Dakota',
    code: 'ND',
    country: 'United States',
  },
  { value: 'Ohio', label: 'Ohio', code: 'OH', country: 'United States' },
  {
    value: 'Oklahoma',
    label: 'Oklahoma',
    code: 'OK',
    country: 'United States',
  },
  { value: 'Oregon', label: 'Oregon', code: 'OR', country: 'United States' },
  {
    value: 'Pennsylvania',
    label: 'Pennsylvania',
    code: 'PA',
    country: 'United States',
  },
  {
    value: 'Rhode Island',
    label: 'Rhode Island',
    code: 'RI',
    country: 'United States',
  },
  {
    value: 'South Carolina',
    label: 'South Carolina',
    code: 'SC',
    country: 'United States',
  },
  {
    value: 'South Dakota',
    label: 'South Dakota',
    code: 'SD',
    country: 'United States',
  },
  {
    value: 'Tennessee',
    label: 'Tennessee',
    code: 'TN',
    country: 'United States',
  },
  { value: 'Texas', label: 'Texas', code: 'TX', country: 'United States' },
  { value: 'Utah', label: 'Utah', code: 'UT', country: 'United States' },
  { value: 'Vermont', label: 'Vermont', code: 'VT', country: 'United States' },
  {
    value: 'Virginia',
    label: 'Virginia',
    code: 'VA',
    country: 'United States',
  },
  {
    value: 'Washington',
    label: 'Washington',
    code: 'WA',
    country: 'United States',
  },
  {
    value: 'West Virginia',
    label: 'West Virginia',
    code: 'WV',
    country: 'United States',
  },
  {
    value: 'Wisconsin',
    label: 'Wisconsin',
    code: 'WI',
    country: 'United States',
  },
  { value: 'Wyoming', label: 'Wyoming', code: 'WY', country: 'United States' },
  {
    value: 'District of Columbia',
    label: 'District of Columbia',
    code: 'DC',
    country: 'United States',
  },
];
