name: Critical Path Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  critical-path-tests:
    name: Critical Path Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Create environment file for tests
        run: |
          echo "🔍 Creating environment file for tests..."

          # Create .env.local with secrets for test environment
          echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> .env.local
          echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> .env.local
          echo "VITE_OPENAI_MODEL=${{ secrets.VITE_OPENAI_MODEL || 'gpt-4o-mini' }}" >> .env.local

          # Note: Tests use mocked Supabase, so secrets are optional for unit tests
          # but may be needed for integration tests
          echo "ℹ️  Using secrets for test environment (tests are mocked)"

      - name: Validate test environment
        run: |
          echo "🔍 Validating test environment setup..."
          echo "✅ Environment variables configured"
          echo "✅ Tests will use mocked Supabase client"
          echo "✅ No real database connections required"

      - name: Run TypeScript check
        run: npx tsc --noEmit --skipLibCheck

      - name: Run AI endpoints unit tests
        run: npm run test -- src/__tests__/api/ai-endpoints.test.ts --run --reporter=verbose
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_OPENAI_MODEL: ${{ secrets.VITE_OPENAI_MODEL || 'gpt-4o-mini' }}
          # Note: OPENAI_API_KEY excluded for security - server-side only

      - name: Run critical path integration tests
        run: npm run test -- src/__tests__/integration/recipe-critical-path.test.ts --run --reporter=verbose
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_OPENAI_MODEL: ${{ secrets.VITE_OPENAI_MODEL || 'gpt-4o-mini' }}
          # Note: OPENAI_API_KEY excluded for security - server-side only

      - name: Test production build
        run: npm run build

      - name: Run core functionality tests
        run: npm run test:core
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_OPENAI_MODEL: ${{ secrets.VITE_OPENAI_MODEL || 'gpt-4o-mini' }}
          # Note: OPENAI_API_KEY excluded for security - server-side only

      - name: Critical path validation summary
        run: |
          echo "🎉 Critical Path Validation Complete!"
          echo "======================================"
          echo "✅ TypeScript compilation"
          echo "✅ AI endpoints structure"
          echo "✅ Recipe CRUD operations"
          echo "✅ Database schema integrity"
          echo "✅ Production build process"
          echo "✅ Core application functionality"
          echo ""
          echo "🚀 Ready for deployment!"
